
```{r}
library(tidyverse)
```

```{r}
tobacco_normalization_data = read.csv("./PCM2_data.csv")

SB2 = tobacco_normalization_data %>% filter(Machine == "SB2")
SB3 = tobacco_normalization_data %>% filter(Machine == "SB3")

tobacco_normalization_data %>% ggplot(aes(x = Machine, y = GFP)) + geom_boxplot() + ggtitle("Before Machine Correction") +
  theme(plot.title = element_text(hjust = 0.5))

SB2_correction = as.data.frame(SB3$GFP / SB2$GFP)
boxplot(SB2_correction) #some need to be filtered
SB2_correction = SB2_correction %>% filter(`SB3$GFP/SB2$GFP` < 1)
boxplot(SB2_correction)


SB2_correction_constant = mean(SB2_correction$`SB3$GFP/SB2$GFP`)

SB2$GFP = SB2$GFP * SB2_correction_constant

tobacco_normalization_data = rbind(SB2, SB3)

tobacco_normalization_data %>% ggplot(aes(x = Machine, y = GFP)) + geom_boxplot() + ggtitle("After Machine Correction") + 
  theme(plot.title = element_text(hjust = 0.5))

```


```{r}
#PCM2_data = read.csv("C:\Users\SophiaTang\Documents\normalization\matthew_annova\PCM2_data.csv")
PCM2_data = read.csv("./PCM2_data.csv")

PCM2_data %>% ggplot(aes(x = Machine, y = GFP)) + geom_boxplot() + ggtitle("Before Machine Correction") + 
  theme(plot.title = element_text(hjust = 0.5))


SB2 = PCM2_data %>% filter(Machine == "SB2")
SB3 = PCM2_data %>% filter(Machine == "SB3")

SB2$GFP = SB2$GFP * SB2_correction_constant

PCM2_data = rbind(SB2, SB3) %>% filter(Strain == "WT")
PCM2_data$Plant = as.factor(PCM2_data$Plant)

PCM2_data %>% ggplot(aes(x = Machine, y = GFP)) + geom_boxplot() + ggtitle("After Machine Correction") + 
  theme(plot.title = element_text(hjust = 0.5))

#Date
PCM2_data %>% ggplot(aes(x = Date, y = GFP)) + geom_boxplot(outlier.shape = NA) + geom_jitter(width = 0.2, height = 0) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

#Date and plant
PCM2_data %>% ggplot(aes(x = Date, y = GFP, fill = Plant)) + geom_boxplot(outlier.shape = NA) + geom_jitter(width = 0.2, height = 0) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

PCM2_data %>% ggplot(aes(x = Date, y = GFP,)) + geom_boxplot(outlier.shape = NA) + geom_jitter(width = 0.2, height = 0, aes(color = Plant)) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

#Just Leaf
PCM2_data %>% ggplot(aes(x = Leaf, y = GFP)) + geom_boxplot(outlier.shape = NA) + geom_jitter(width = 0.2, height = 0) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

PCM2_data %>% group_by(Date, Plant) %>% summarize(mean = mean(GFP), PlantAverage = "Plant Average") %>% ggplot(aes(x = PlantAverage, y = mean)) + 
  geom_boxplot(outlier.shape = NA) + geom_jitter(width = 0.2, height = 0, aes(color = Date)) + ylim(c(0, NA))

#Just week
plant_only = PCM2_data %>% group_by(Date, Plant) %>% summarize(GFP_average = mean(GFP), Group = "Plant Average", sd = sd(GFP)) %>% select(GFP_average, Group, sd)
 
week_only = PCM2_data %>% group_by(Date) %>% summarize(GFP_average = mean(GFP), Group = "Week Average", sd = sd(GFP))

Week_and_plant = rbind(plant_only, week_only)

Week_and_plant %>% ggplot(aes(x = Group, y = GFP_average)) + geom_jitter(width = 0.2, height = 0) +
  geom_errorbar(aes(ymin = GFP_average - sd, ymax = GFP_average + sd), width = 0.2)

Week_and_plant %>%
  ggplot(aes(x = Group, y = GFP_average)) +
  geom_jitter( position = position_jitter(0.3)) +  # Adjust jitter position
  geom_errorbar(aes(ymin = GFP_average - sd, ymax = GFP_average + sd), width = 0.01, position = position_jitter(0.3))

ggplot(Week_and_plant, aes(x = Group, y = GFP_average, color = Group)) +
  geom_jitter(position = position_jitterdodge(0.3)) +
  geom_errorbar(aes(ymin = GFP_average - sd, ymax = GFP_average + sd), width = 0.05, position = position_jitterdodge(0.3)) +
  geom_point(aes(y = GFP_average), position = position_jitterdodge(0.3), size = 2) 
 


```

```{r}
#Variance analysis
PCM2_data$Unique_plant_ID = as.factor(PCM2_data$Unique_plant_ID)
PCM2_data$Date = as.factor(PCM2_data$Date)
PCM2_data$Well = as.factor(PCM2_data$Well)


#Multiple regression analysis
model <- lm(GFP ~ Date + Leaf + Unique_plant_ID, data = PCM2_data)
summary(model)

#Multiple regression analysis
model <- lm(GFP ~ (Date + Leaf), data = PCM2_data)
summary(model)

model <- lm(GFP ~ (Leaf), data = PCM2_data)
summary(model)

#ANOVA
anova_model <- aov(GFP ~ Date + Leaf + Unique_plant_ID, data = PCM2_data)
anova_model_summary = summary(anova_model)
F_values = anova_model_summary[[1]]$`F value`
Sum_squares = anova_model_summary[[1]]$`Sum Sq`
Mean_squares = anova_model_summary[[1]]$`Mean Sq`


F_value_data = as.data.frame(list(Variable = c("Date", "Leaf", "Plant"), F_value = c(67.51, 70.411, 3.583)))
F_value_data$Variable = factor(F_value_data$Variable, levels = c("Plant", "Date", "Leaf"))
F_value_data %>% ggplot(aes(x = Variable, y = F_value)) + geom_col()

Sum_squares_data = as.data.frame(list(Variable = c("Date", "Leaf", "Plant", "Residual Variance"), Sum_squares = Sum_squares))
Sum_squares_data$Variable = factor(Sum_squares_data$Variable, levels = c("Leaf", "Plant", "Date", "Residual Variance"))
Sum_squares_data = Sum_squares_data %>% mutate(Total_variance = sum(Sum_squares)) %>% mutate(Percent_Variance = 100 * Sum_squares / Total_variance)

Sum_squares_data %>% ggplot(aes(x = Variable, y = Percent_Variance)) + geom_col() + ylab("Percent Variance Explained") + xlab("Variance Source") + 
  ggtitle("Sources of Variability in Tobacco Transient Assays") + theme(plot.title = element_text(hjust = 0.5))





mean_squares_data = as.data.frame(list(Variable = c("Date", "Leaf", "Plant", "Residual Variance"), mean_squares = Mean_squares))
mean_squares_data$Variable = factor(mean_squares_data$Variable, levels = c("Leaf", "Plant", "Date", "Residual Variance"))
mean_squares_data %>% ggplot(aes(x = Variable, y = mean_squares)) + geom_col()

Just_top = PCM2_data %>% filter(Leaf == "Top")
Just_bottom = PCM2_data %>% filter(Leaf == "Bottom")
model <- aov(GFP ~ Date + Unique_plant_ID, data = Just_bottom)
summary(model)
model <- aov(GFP ~ Date + Unique_plant_ID, data = Just_top)
summary(model)


write.csv(Sum_squares_data, 'benthi_variability.csv')
```

